/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.diviso.graeshoppe.client.prod.api;

import com.diviso.graeshoppe.client.prod.model.StockDiaryDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-06-26T12:37:09.495+05:30[Asia/Calcutta]")

@Api(value = "StockDiaryResource", description = "the StockDiaryResource API")
public interface StockDiaryResourceApi {

    @ApiOperation(value = "createStockDiary", nickname = "createStockDiaryUsingPOST", notes = "", response = StockDiaryDTO.class, tags={ "stock-diary-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StockDiaryDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/stock-diaries",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<StockDiaryDTO> createStockDiaryUsingPOST(@ApiParam(value = "stockDiaryDTO" ,required=true )  @Valid @RequestBody StockDiaryDTO stockDiaryDTO);


    @ApiOperation(value = "createStockOfProduct", nickname = "createStockOfProductUsingPOST", notes = "", response = StockDiaryDTO.class, tags={ "stock-diary-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StockDiaryDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/stock-diaries/productStock",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<StockDiaryDTO> createStockOfProductUsingPOST(@ApiParam(value = "stockDiaryDTO" ,required=true )  @Valid @RequestBody StockDiaryDTO stockDiaryDTO);


    @ApiOperation(value = "deleteStockDiary", nickname = "deleteStockDiaryUsingDELETE", notes = "", tags={ "stock-diary-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/stock-diaries/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteStockDiaryUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllStockDiaries", nickname = "getAllStockDiariesUsingGET", notes = "", response = StockDiaryDTO.class, responseContainer = "List", tags={ "stock-diary-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StockDiaryDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/stock-diaries",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<StockDiaryDTO>> getAllStockDiariesUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getStockDiaryByProductId", nickname = "getStockDiaryByProductIdUsingGET", notes = "", response = StockDiaryDTO.class, responseContainer = "List", tags={ "stock-diary-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StockDiaryDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/stock-diaries/product/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<StockDiaryDTO>> getStockDiaryByProductIdUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getStockDiary", nickname = "getStockDiaryUsingGET", notes = "", response = StockDiaryDTO.class, tags={ "stock-diary-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StockDiaryDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/stock-diaries/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<StockDiaryDTO> getStockDiaryUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchStockDiaries", nickname = "searchStockDiariesUsingGET", notes = "", response = StockDiaryDTO.class, responseContainer = "List", tags={ "stock-diary-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StockDiaryDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/stock-diaries",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<StockDiaryDTO>> searchStockDiariesUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateStockDiary", nickname = "updateStockDiaryUsingPUT", notes = "", response = StockDiaryDTO.class, tags={ "stock-diary-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StockDiaryDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/stock-diaries",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<StockDiaryDTO> updateStockDiaryUsingPUT(@ApiParam(value = "stockDiaryDTO" ,required=true )  @Valid @RequestBody StockDiaryDTO stockDiaryDTO);

}
