/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.diviso.graeshoppe.client.product.api;

import com.diviso.graeshoppe.client.product.model.StockLineDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-04-30T16:24:43.095+05:30[Asia/Calcutta]")

@Api(value = "StockLineResource", description = "the StockLineResource API")
public interface StockLineResourceApi {

    @ApiOperation(value = "createStockLine", nickname = "createStockLineUsingPOST", notes = "", response = StockLineDTO.class, tags={ "stock-line-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StockLineDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/stock-lines",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<StockLineDTO> createStockLineUsingPOST(@ApiParam(value = "stockLineDTO" ,required=true )  @Valid @RequestBody StockLineDTO stockLineDTO);


    @ApiOperation(value = "deleteStockLine", nickname = "deleteStockLineUsingDELETE", notes = "", tags={ "stock-line-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/stock-lines/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteStockLineUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllStockLines", nickname = "getAllStockLinesUsingGET", notes = "", response = StockLineDTO.class, responseContainer = "List", tags={ "stock-line-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StockLineDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/stock-lines",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<StockLineDTO>> getAllStockLinesUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getStockLine", nickname = "getStockLineUsingGET", notes = "", response = StockLineDTO.class, tags={ "stock-line-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StockLineDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/stock-lines/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<StockLineDTO> getStockLineUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchStockLines", nickname = "searchStockLinesUsingGET", notes = "", response = StockLineDTO.class, responseContainer = "List", tags={ "stock-line-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StockLineDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/stock-lines",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<StockLineDTO>> searchStockLinesUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateStockLine", nickname = "updateStockLineUsingPUT", notes = "", response = StockLineDTO.class, tags={ "stock-line-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = StockLineDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/stock-lines",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<StockLineDTO> updateStockLineUsingPUT(@ApiParam(value = "stockLineDTO" ,required=true )  @Valid @RequestBody StockLineDTO stockLineDTO);

}
